# Generated by Django 4.1.1 on 2022-09-07 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0002_alter_room_capacity_alter_room_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Event Name")),
                ("date", models.DateField(verbose_name="Event date")),
                ("private", models.BooleanField(default=False)),
                ("customers", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="rooms.room"
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "room")},
            },
        ),
    ]
